-- ====================================================================
-- WestRP Karma — Shared Types (EmmyLua Strict Annotations)
-- File: shared/types.lua
-- ====================================================================

---@class KarmaTier
---@field id string
---@field name string
---@field minKarma integer
---@field maxKarma integer
---@field shopDiscount number
---@field bountyEligible boolean
---@field baseBounty number

---@class BallisticDetails
---@field weaponCategory "REVOLVER" | "PISTOL" | "REPEATER" | "RIFLE" | "SHOTGUN" | "SNIPER" | "BOW" | "THROWN" | "EXPLOSIVE" | "MELEE" | "UNARMED"
---@field ammoHash integer?
---@field damageBone integer?
---@field isHeadshot boolean
---@field distanceMeters number
---@field isBleedoutPromotion boolean

---@class CombatActionPayload
---@field targetType "CIVILIAN" | "LAWMAN" | "PLAYER" | "ANIMAL"
---@field actionType "KILL" | "KNOCKOUT" | "ASSAULT"
---@field initiative "UNPROVOKED" | "SELF_DEFENSE"
---@field isNegative boolean
---@field weaponHash integer
---@field victimServerId integer?
---@field wasKnockedOut boolean
---@field wasAssaulted boolean
---@field isHeadshot boolean?
---@field distanceMeters number?
---@field weaponCategory string?
---@field isBleedoutPromotion boolean?

---@class CharacterKarmaData
---@field charIdentifier integer
---@field source integer
---@field karma integer
---@field tier KarmaTier
---@field isDirty boolean
---@field lastSaved integer
