-- ====================================================================
-- WestRP Karma — Shared Types (EmmyLua Strict Annotations)
-- File: shared/types.lua
-- ====================================================================

---@class KarmaTier
---@field id string
---@field name string
---@field minKarma integer
---@field maxKarma integer
---@field shopDiscount number
---@field bountyEligible boolean
---@field baseBounty number

---@class CombatActionPayload
---@field targetType "CIVILIAN" | "LAWMAN" | "PLAYER" | "ANIMAL"
---@field actionType "KILL" | "KNOCKOUT" | "ASSAULT"
---@field initiative "UNPROVOKED" | "SELF_DEFENSE"
---@field isNegative boolean
---@field weaponHash integer
---@field victimServerId integer?
---@field wasKnockedOut boolean
---@field wasAssaulted boolean

---@class CharacterKarmaData
---@field charIdentifier integer
---@field source integer
---@field karma integer
---@field tier KarmaTier
---@field isDirty boolean
---@field lastSaved integer
